import type { NextPage } from "next"
import Head from "next/head"
import styles from "../styles/Home.module.css"
import MainGame from "../components/MainGame"

interface Props {
  wordList: string[]
  mainWord: string
  updateLength: (number: number) => void
  wordLength: number
}

const Home: NextPage<Props> = ({
  wordList,
  mainWord,
  updateLength,
  wordLength,
}) => {
  return (
    <div>
      <Head>
        <title>Word Cracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainGame
          wordLength={wordLength}
          mainWord={mainWord}
          updateLength={updateLength}
          wordList={wordList}
        />
      </main>
      <footer className={styles.footer}>
        <p>Powered by PDX-McCord</p>
      </footer>
    </div>
  )
}

export default Home
