import { useState } from "react"
import type { NextPage } from "next"
import Head from "next/head"
import { Text, Flex, Box, Container, Button, Input } from "@chakra-ui/react"
import LetterPicker from "../components/LetterPicker"
import GuessRow from "../components/GuessRow"
import { LetterState } from "../types"
import styles from "../styles/Home.module.css"
import { evalGuess, numberLimiter } from "../utils"

interface Props {
  wordList: string[]
  mainWord: string
  updateLength: (number: number) => void
  wordLength: number
}

const Home: NextPage<Props> = ({
  wordList,
  mainWord,
  updateLength,
  wordLength,
}) => {
  const [letterSet, setLetterSet] = useState<LetterState[]>([])
  const [history, setHistory] = useState<LetterState[][]>([])
  const [inputValue, setInputValue] = useState<number>(wordLength)

  console.log("words", mainWord)

  const addALetter = (l: string) => {
    if (letterSet.length < wordLength) {
      const newLetterSet: LetterState[] = [
        ...letterSet,
        { letter: l, state: "guess" },
      ]
      setLetterSet(newLetterSet)
    }
  }

  const makeGuess = () => {
    if (letterSet.length === wordLength && history.length !== wordLength + 1) {
      const evalLetters = evalGuess(mainWord, letterSet)
      const newRow = [evalLetters, ...history]
      setHistory(newRow)
      setLetterSet([])
    }
  }

  const removeLastLetter = () => {
    if (letterSet.length >= 1) {
      const newLetterSet: LetterState[] = [...letterSet].slice(
        0,
        letterSet.length - 1
      )
      setLetterSet(newLetterSet)
    }
  }

  const handleStartOver = () => {
    setHistory([])
  }

  return (
    <div>
      <Head>
        <title>Word Cracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <Flex justifyContent="center">
            <Text as="h1" fontSize="36">
              Word Cracker
            </Text>
          </Flex>
          <Box>Litter guess</Box>
          <Box>
            <GuessRow letters={letterSet} index={0} />
            {history.map((g, index) => (
              <GuessRow
                key={`${index}-${index}`}
                letters={g}
                index={index + 1}
              />
            ))}
          </Box>
          <LetterPicker
            addALetter={addALetter}
            makeGuess={makeGuess}
            removeLastLetter={removeLastLetter}
            isGuessReady={letterSet.length !== wordLength}
          />
          <Button onClick={handleStartOver}>Start Over</Button>
        </Container>
      </main>
      <Box w="50%">
        <Text>Word Length</Text>
        <Input
          type="number"
          value={inputValue}
          onChange={(e) => {
            numberLimiter(parseInt(e.target.value), setInputValue)
            updateLength(parseInt(e.target.value))
          }}
        />
      </Box>
      <footer className={styles.footer}>
        <p>Powered by PDX-McCord</p>
      </footer>
    </div>
  )
}

export default Home
